# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 486dd795cc51b1b0853332bef922c3fd2ba2937d37cff6614380ea461e3f0147bed179e7699f880bb08dfd761dcca648643e334bea4a5dfae2b03f2f93ce08d1

test:
  secret_key_base: 09df45cbf6d4ae2d0d13cc076877026dbeeb97ac153af4bb365a79f90ab90b0925fa79168a0da4131b69a58efbb931f15f6eadaff02e00737c2b4d7a717108e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
